apiVersion: apps/v1
kind: Deployment
metadata:
  name: realtime-chatapp-frontend-deployment
  labels:
    app: realtime-chatapp-frontend
  namespace: realtime-chatapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: realtime-chatapp-frontend
  template:
    metadata:
      labels:
        app: realtime-chatapp-frontend

    spec:
      containers:
        - name: realtime-chatapp-frontend
          image: 023703348962.dkr.ecr.ap-south-1.amazonaws.com/realtime-chatapp-frontend:0863012b94f6a4a4fed94dc4ccc49ebcc444e020-17
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          # env:
          #   - name: VITE_BACKEND_URL
          #     value: "http://mern-backend-service.mern-app.svc.cluster.local:5000"